// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGicovSWFsr0rRZjShMn63zIPcnqlxdo4',
    appId: '1:235099355517:web:ec1bb1cbf4562f9b2db414',
    messagingSenderId: '235099355517',
    projectId: 'skinoff-e3ee6',
    authDomain: 'skinoff-e3ee6.firebaseapp.com',
    storageBucket: 'skinoff-e3ee6.firebasestorage.app',
    measurementId: 'G-RR4FNNYME9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVcA4sOlmURm2LTAzlQ5b_DyNYGEcppYM',
    appId: '1:235099355517:android:f8029ee49f9704962db414',
    messagingSenderId: '235099355517',
    projectId: 'skinoff-e3ee6',
    storageBucket: 'skinoff-e3ee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoD9tUTWkVjGeGyWjU1gaDJD9vu1SS5aQ',
    appId: '1:235099355517:ios:a28677f2e90ef56f2db414',
    messagingSenderId: '235099355517',
    projectId: 'skinoff-e3ee6',
    storageBucket: 'skinoff-e3ee6.firebasestorage.app',
    iosBundleId: 'com.example.skinup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoD9tUTWkVjGeGyWjU1gaDJD9vu1SS5aQ',
    appId: '1:235099355517:ios:a28677f2e90ef56f2db414',
    messagingSenderId: '235099355517',
    projectId: 'skinoff-e3ee6',
    storageBucket: 'skinoff-e3ee6.firebasestorage.app',
    iosBundleId: 'com.example.skinup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGicovSWFsr0rRZjShMn63zIPcnqlxdo4',
    appId: '1:235099355517:web:5360c531cfa014082db414',
    messagingSenderId: '235099355517',
    projectId: 'skinoff-e3ee6',
    authDomain: 'skinoff-e3ee6.firebaseapp.com',
    storageBucket: 'skinoff-e3ee6.firebasestorage.app',
    measurementId: 'G-HHFGLBVZD4',
  );

}